//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAL_Distributors_Web_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public string CUSTOMER_NUM { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string STREET { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string POSTAL_CODE { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public Nullable<decimal> CREDIT_LIMIT { get; set; }
        public string REP_NUM { get; set; }
    }
}
