//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquariumService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fish
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Type { get; set; }
    
        public virtual FishType FishType { get; set; }
    }
}
