<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="display_answer.aspx.cs" Inherits="Aquarium_Csharp_With_Database.display_answer" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <br />
        Water (gallons):<br />
        <asp:Label ID="gallonsLabel"  runat="server" Font-Size="XX-Large" Height="35px" Width="105px"></asp:Label>
        <br /><br />
        <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/default.aspx">Home Page</asp:HyperLink>
        <br />
        <br />
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" 
            AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="SqlDataSource1" 
            AutoGenerateEditButton="True">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="Name" HeaderText="Name" ReadOnly="true" SortExpression="Name" />
                <asp:BoundField DataField="Description" HeaderText="Description" ReadOnly="true" SortExpression="Description" />
                <asp:BoundField DataField="Cost" HeaderText="Cost" SortExpression="Cost" />
                 <%--add a manual delete button (instead of using AutoGenerateDeleteButton--%>
                <asp:TemplateField>
                    <ItemTemplate>
                        <asp:LinkButton runat="server"
                            OnClientClick="return confirm('Confirm Delete:');"
                            CommandName="Delete">Delete
                        </asp:LinkButton>
                    </ItemTemplate>
                </asp:TemplateField>                
            </Columns>           
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:AquariumConnectionString %>" 
            SelectCommand="SELECT Id, Name, Description, Cost FROM Fish F, FishType FT WHERE F.Type = FT.Type"
            InsertCommand="INSERT INTO fish values(@Name,@Cost,@Type)"
            UpdateCommand="UPDATE fish SET Cost=@Cost WHERE Id=@Id"
            DeleteCommand="DELETE FROM fish WHERE Id=@Id" ProviderName="<%$ ConnectionStrings:AquariumConnectionString.ProviderName %>">
            
            <UpdateParameters>
                <asp:Parameter Name="Id" />
                <asp:Parameter Name="Cost" />
            </UpdateParameters>
            <DeleteParameters>
                <asp:Parameter Name="Id" />                
            </DeleteParameters>
        </asp:SqlDataSource>

        <br/>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:AquariumConnectionString %>" 
            SelectCommand="SELECT SUM(Cost) AS TotalCost, count(id) AS TotalNumber  FROM Fish">
        </asp:SqlDataSource>
       
        <asp:Button ID="totInvButton" runat="server" Text="Total Inventory" OnServerClick="totInvButton_Click" OnClick="totInvButton_Click"/>
        &nbsp;&nbsp;&nbsp;&nbsp;
       
        <asp:Button ID="addFishButton" runat="server" Text="Add a Fish" OnServerClick="totInvButton_Click"/>
        <br />
        <br />
        Total Cost: 
        <asp:Label ID="totCostLabel" runat="server" Text=""></asp:Label>
        <br />
        Total number:
        <asp:Label ID="totNumberLabel" runat="server"></asp:Label>
        <br />
        <br />  
        <asp:Button ID="Button1" runat="server" Text="Single Fish Search" OnClick="Button1_Click" />
        </form>
</body>
</html>
