//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheapLoansProjectPart3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int LoanNum { get; set; }
        public string CustName { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<decimal> AnnualIntRate { get; set; }
        public Nullable<int> NumPayments { get; set; }
    }
}
